title: 雨沐苍树
description: My personal blog
permalink: /:year/:month/:day/:title.html
# paginate: 10
markdown: kramdown
highlighter: rouge

# 作者信息
author: 
  github: http://github.com/shen445122
  email: shenzr668@gmail.com
  #link:
  #weibo:
  #music:
  #linkedin:

# 站点信息
baseurl: "" 
url: "http://shen445122.github.io" 
rss_url: /pages/feed.xml
production_url : http://shen445122.github.io
production_sitename : shen445122.github.io


# avatar头像及Favicon
gavatar: /public/img/tree.png
favicon: /public/img/favicon.ico


# disqus 设置
disqus:
  shortname: shen445122


# google analytics 设置
ga:
  id: UA-76066813-1
  url: shen445122.github.io


# Jekyll-Bootstrap 相关页面
JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : /assets/themes
  archive_path: pages/archive.html
  categories_path : pages/categories.html
  tags_path : pages/tags.html
  rss_path : pages/rss.xml


# 主题设置，自动激活某个标签
active: 读书


# 首页除了最新文章外显示分类
cates: 
  - Linux

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  categories: 分类
  value: 价值

# 其他备用配置
sass:
  style: compressed
