# Site settings
title: 雨沐苍树
email: shenzr668@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  雨沐苍树1

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# url
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shen445122.github.io" # the base hostname & protocol for your site
rss_url: /pages/feed.xml
production_url : http://shen445122.github.io
production_sitename : shen445122.github.io

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
# twitter: NAME
# weibo:    ID
github: shen445122
# codepen:  username
# dribbble: username

# avatar头像及Favicon
#avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico
favicon: favicon.ico

# disqus 设置
#disqus:
#  shortname: 

# google analytics 设置
ga:
  id: UA-76066813-1
  url: shen445122.github.io

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : /assets/themes
  archive_path: pages/archive.html
  categories_path : pages/categories.html
  tags_path : pages/tags.html
  rss_path : pages/rss.xml

  #comments :
  #  provider : duoshuo
  #  duoshuo :
  #    short_name : shen445122

  #analytics :
  #  provider : google
  #  google :
  #      tracking_id : 'UA-76066813-1'

  #sharing :
  #  provider : duoshuo
