#!/bin/bash
## File Name: local-server.sh
## Author:  shen.szr   mail: shen.szr@alibaba-inc.com
## Description: 
## Created Time: Tue 05 Apr 2016 09:56:05 PM CST

#!/bin/sh
CODE_DIR=/home/smart/htdocs/shen445122.github.io

if [ -d ${CODE_DIR} ];then
  cd ${CODE_DIR}
  rm -rf _site/*
  jekyll serve -H 0.0.0.0
fi

#检查错误
#jekyll build --trace
